require "pry"

require_relative "advent_of_code/shared/list"
require_relative "advent_of_code/shared/value"
require_relative "advent_of_code/shared/number_value"
require_relative "advent_of_code/shared/model"

require_relative "advent_of_code/domain/depth"
require_relative "advent_of_code/domain/position"
require_relative "advent_of_code/domain/submarine"

require_relative "advent_of_code/day_one"
require_relative "advent_of_code/day_two"
require_relative "advent_of_code/day_three"
require_relative "advent_of_code/day_four"
require_relative "advent_of_code/day_five"
require_relative "advent_of_code/day_six"
require_relative "advent_of_code/day_seven"
require_relative "advent_of_code/day_eight"
require_relative "advent_of_code/day_nine"
require_relative "advent_of_code/day_ten"
require_relative "advent_of_code/day_eleven"
require_relative "advent_of_code/day_twelve"
require_relative "advent_of_code/day_thirteen"
require_relative "advent_of_code/day_fourteen"
require_relative "advent_of_code/day_fifteen"
require_relative "advent_of_code/day_sixteen"
require_relative "advent_of_code/day_seventeen"
require_relative "advent_of_code/day_eighteen"
require_relative "advent_of_code/day_nineteen"
require_relative "advent_of_code/day_twenty"
require_relative "advent_of_code/day_twenty_one"
require_relative "advent_of_code/day_twenty_two"
require_relative "advent_of_code/day_twenty_three"
require_relative "advent_of_code/day_twenty_four"
require_relative "advent_of_code/day_twenty_five"

module AdventOfCode
end
